### ISSUE TITLE
Create .podspec

### ISSUE THREAD

**Issue by msnelling** [brunow/FormKit.m#1]
Since you're removing FormKit from BaseKit can you create a .podspec for FormKit.m (and TableKit.m) please?

**Comment by brunow** [comment]
It's on my todo list, but first I need to add some thing before release a version and create pods.

**Comment by hoop33** [comment]
Any movement on this? Can I help?

**Comment by brunow** [comment]
I've added a podspec to the repository, but didn't push it to Cocoapods (You can do it if you want).

To use it now:
pod "FormKit.m", :git => "https://github.com/brunow/FormKit.m.git", :tag => "0.1.1"

**Comment by hoop33** [comment]
Awesome--thanks!

Bruno Wernimont wrote:
