### ISSUE TITLE
Scrolling only works with UITableViewController

### ISSUE THREAD

**Issue by ghost** [brunow/FormKit.m#13]
When using FomKit Demo, the scrolling to show the actual "in focus" field only works, because the UITableView is embedded in a UITableViewController. It does not work, if using an UIViewController and add a UITableView as property: The scrollview does not get, that the keyboard showed up and so the in focus maybe hidden.
 I made a demo project and added also a possible solution in form of the OS Component TPKeyboardAvoiding, hosted here on github:
https://github.com/michaeltyson/TPKeyboardAvoiding

Just see the fork at:
https://github.com/appcominteractive/FormKit.m
and checkout feature_autoScrollingWithoutUITableViewController branch. 

Question is, if this should be part of FormKit or at least the FormKit Documentation (as warning).

Regards,
Christian

**Comment by crivera** [comment]
oh man thanks so much for your solution... i had exactly the same issue !

**Comment by tudormunteanu** [comment]
I've found another solution and it goes along these lines: https://gist.github.com/tudormunteanu/6365593
