### ISSUE TITLE
Missing synthesize

### ISSUE THREAD

**Issue by link82** [brunow/FormKit.m#14]
Hello, I'm trying to migrate from BaseKit formMapping to FormKit.

I noticed a lot of new properties are missing their getter / setter methods and, in fact, the compiler complains they need to be synthesized.

Anybody else is having this issue? In the meantime i'll try if synthesizing it works or not.

Thanks! :P

**Comment by link82** [comment]
It seems to work correctly synthesizing the missing properties, anyway it looks strange to me nobody else found this issue before.

**Comment by brunow** [comment]
Yes with the new xcode you don't need to add synthesizing anymore, because of that I forget to add it.

**Comment by link82** [comment]
Oops, indeed i'm still using Xcode 4.3.2

**Comment by link82** [comment]
Ok i'll close the issue, thank you. :)
