### ISSUE TITLE
Customize Cells layout

### ISSUE THREAD

**Issue by link82** [brunow/FormKit.m#16]
Hello, I'm trying to figure out how to customize the aspect of table cells with FormKit without losing the mapping features.

I tried using the method  mapCustomCell: identifier: rowHeight: willDisplayCellBlock: but i cannot set the "type" attribute in any way.

Do I need to subclass the FK Cells?

Thank you.

**Comment by rpitting** [comment]
If you use mapCustomCell:..., why do you still need the type-attribute?

The method is useful for extending the build-in field types with your own (and to avoid subclassing FKFormMapper).

**Comment by link82** [comment]
Because I would like to use the default behavior (for example it will setup and push a viewController in the case I choose the FKFormAttributeMappingTypeBigText mapping type.

I just want to customize font / size / background of FormKit default cells without loosing the rest and I have no idea where to start from.

**Comment by rpitting** [comment]
Have a look at FKFormMapping: it contains properties for cell prototypes (e.g. "textFieldClass"). Replace it with your custom subclass e.g. of FKTextField. HTH

**Comment by link82** [comment]
Thank you! Tomorrow I'll try to destroy everything :panda_face:

**Comment by shams-ahmed** [comment]
@brunow post a bit old, but is subclassing still the only option if i like to only change font, background color?

**Comment by brunow** [comment]
Yes at the moment it's the only option. But you've some option as changing cell background color label color or value color. But for changing font you've to subclass

**Comment by pkasson** [comment]
How do you change the font of a uitextfield for a given mapping ?   I have a textfield that has too small text, and want to change its appearance.

Thanks.
