### ISSUE TITLE
Mapping to non-NSString  for picker

### ISSUE THREAD

**Issue by doronkatz** [brunow/FormKit.m#18]
Hey there,

im trying to map my object for a picker, which looks something like this:

```
    [formMapping mapAttribute:@"appPlaceCategory"
                        title:@"Type of practice"
                 showInPicker:YES
            selectValuesBlock:^NSArray *(id value, id object, NSInteger *selectedValueIndex){
                *selectedValueIndex = 1;
                return self.categories;

            } valueFromSelectBlock:^id(id value, id object, NSInteger selectedValueIndex) {
                return [self.categories objectAtIndex:selectedValueIndex];

            } labelValueBlock:^id(id value, id object) {
                return value;

            }];
```

Now, the problem is, appPlaceCategory or AppPlace.AppPlaceCategory is not a string, but rather of an object type (i.e Category). I can't seem to get this to map properly.

Any help would be appreciated.

Thanks!

**Comment by rpitting** [comment]
Hi Doron,

you would have to convert your object types into string to display them in the picker.

This can be done in the labelValueBlock, e.g. like this:

``` obj-c
labelValueBlock:^id(id value, id object) {
  AppPlace* place = (AppPlace*)object;
  [appPlace displayNameForCategory:value];
}
```

Therefore, you should write a convert-method that returns e.g. localized strings or your categories.
