### ISSUE TITLE
Exception in [FKFormMapper titleForHeaderInSection]

### ISSUE THREAD

**Issue by msnelling** [brunow/FormKit.m#2]
I'm having trouble with FormKit.m. I was able to use BaseKit successfully but require the custom cell functionality.
I get an EXC_BAD_ACCESS exception in [FKFormMapper titleForHeaderInSection] when scrolling or moving to a new cell.
I can email a sample workspace if you want.

**Comment by brunow** [comment]
Do you have a section ? Because at the moment you need to add fields into section otherwise it will not work.

[mapping sectiontWithTitle:@"Information section" identifier:@"info"];

I you don't want to add a title leave it with an empty string

**Comment by msnelling** [comment]
Yes I have a section. My trivial project is very similar to your example.

**Comment by brunow** [comment]
Can you upload your example on dropbox or anything else ?

**Comment by msnelling** [comment]
Here's the workspace. It uses Cocoapods which links to the Git repository so you'll need to run 'pod install' first.
http://dl.dropbox.com/u/3706463/FormKitTest.zip

**Comment by msnelling** [comment]
Were you able to download the sample project?

**Comment by brunow** [comment]
Yes, you must add "s.requires_arc = true" to your podfile because by default pods are arc that's why memory is released. But I don't know why if you add "require_arc" the project will not compile maybe a bug from cocoapods ?
Try to drag and dropp all formkit file to your project without using cocoapods.

**Comment by msnelling** [comment]
I tried adding the "s.requires_arc = true" and you're right it doesn't compile, all the flags look correct though.
It works when I just add the files directly in and don't use Cocoapods.
Seems to be an Cocoapods issue?

**Comment by brunow** [comment]
I think so but not sure
