### ISSUE TITLE
Formkit's podspec incompatible with latests CocoaPods version?

### ISSUE THREAD

**Issue by iljaiwas** [brunow/FormKit.m#24]
Hi there,

I'm getting an error after having updated my cocoapods installation to v 0.20.2 when trying to include FormKit in my Podfile.

I have a very simple Podfile, which looks like this:

```
platform :ios, '5.0'
pod 'AFNetworking'
pod 'MACollectionUtilities'
pod 'FormKit.m', :git => "https://github.com/brunow/FormKit.m.git", :tag => "0.2.0"
```

Now I'm getting the following error when doing pod --verbose install

```
Pod::DSLError - Invalid `FormKit.m.podspec` file: [!] Unsupported version requirements
 #
 #  from /Users/Account/source/Project/Pods/Local Podspecs/FormKit.m.podspec:14
 #  -------------------------------------------
 #    s.dependency 'ActionSheetPicker2'
 >    s.dependency 'BWSelectViewController', :git => "https://github.com/brunow/BWSelectViewController.git", :tag => "0.1.1"
 #  end
#  -------------------------------------------
```

I checked all three dependency, and they can be included in the Podfile without projects?

Any ideas what might be the problem?

Regards,
Ilja

**Comment by alloy** [comment]
This has changed since [0.17.2](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#0172). The related ticket is: https://github.com/CocoaPods/CocoaPods/issues/787.

**Comment by alloy** [comment]
(Actually it didn’t really change, it was just undefined before.)

**Comment by alloy** [comment]
Ugh, actually that’s not the right ticket. I’m looking the right one up.

**Comment by alloy** [comment]
It was [0.17.0.rc1](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#rc1):

> External sources are not supported in the dependencies of specifications anymore. Actually they never have been supported, they just happened to work.

**Comment by iljaiwas** [comment]
Thanks for letting me know.

Bruno, do you have time to updated your podspecs to the new requirements?

**Comment by GarPit** [comment]
+1

**Comment by ryanholden88** [comment]
+1

Love FormKit! Thank you for this library, compatibility with the latest cocoapod spec would get it even closer to perfect :)

**Comment by fulldecent** [comment]
Is anyone using a workaround here?

**Comment by fulldecent** [comment]
Fix is:
- accept https://github.com/brunow/BWSelectViewController/pull/1 
- submit BWSelectViewController to CocoaPods
- update this podspec to use CocoaPods

**Comment by XavierDK** [comment]
I have created a temporary solution.

Just add my custom podspec repo : 

```
pod repo add MyCocoapods https://github.com/XavierDK/MyCocoapods.git
```

And add this podspec manually to your project : 

```
Pod::Spec.new do |s|
  s.name         = "FormKit.m"
  s.version      = "0.3"
  s.requires_arc = true
  s.summary      = "FormKit.m is a library that helps building form with table view."
  s.description  = "FormKit.m is a library that helps building form with table view. 
https://twitter.com/brunowernimont"
  s.homepage     = "https://github.com/brunow/FormKit.m"
  s.license      = 'MIT'
  s.author       = { "Bruno Wernimont" => "http://brunowernimont.be" }
  s.platform     = :ios, '6.0'
  s.source       = { :git => "https://github.com/brunow/FormKit.m.git", :commit => 'd89ae4c2119bfc726e2c7c8b556b16183ea32ebf' }
  s.source_files = 'FormKit/*', 'FormKit/Fields/*'
  s.dependency 'ActionSheetPicker2'
  s.dependency 'BWSelectViewController'
  s.dependency 'BWLongTextViewController'
end
```

After that just make a 'pod install' ;).

**Comment by brunow** [comment]
I'm sorry but unfortunately I don't have time to fix this at the moment.
I'm focusing my time on developing new feature.

**Comment by rpitting** [comment]
Would it be a solution to just add BWSelectViewController to FormKit.m? It's just two files, and it would solve the issue.

**Comment by iljaiwas** [comment]
Have you tried using this instead of FormKit: https://github.com/nicklockwood/FXForms

**Comment by rpitting** [comment]
Well, @iljaiwas, I think everyone can decide that for himself. But it's does not help to solve this issue.

**Comment by brunow** [comment]
Including BWSelectViewController is not a good solution, because if you use pod 'formkit' and pod 'BWSelectViewController' you'll have duplicate class.

I've recently updated BWSelectViewController pod but not submited it to cocoapods.
If you want @iljaiwas you can submit it to cocoapods.

**Comment by shams-ahmed** [comment]
Any update on this topic? 

is @XavierDK the only current workaround?
