### ISSUE TITLE
Field Validation

### ISSUE THREAD

**Issue by msnelling** [brunow/FormKit.m#3]
Do you have any plans to add form validation blocks to fields? It would be nice to be able to display a badge on a cell or a tooltip indicating an invalid value.

**Comment by brunow** [comment]
Yes it would be great to add validation. It's planned, but not in the near future.

**Comment by msnelling** [comment]
Thanks. In the meantime how would you suggest I add this myself, where would I hook in my UITableViewController class?

**Comment by brunow** [comment]
For now it will be hard to add it, because if you want to show error message you need bigger cels than now. And even worst you w'll need to change the cels height if you have error or not dynamically.

**Comment by msnelling** [comment]
If I forget changing the cells for now and use some other notification system, how can I get notified when a field has ended editing?

**Comment by brunow** [comment]
With FormKit you cannot. But there are keyboard global notification observer (UIKeyboardWillHideNotification) maybe it can help you

**Comment by rpitting** [comment]
I will look into some kind of simple validation, at least being able to mark labels with invalid values with a given color

Later on, you can think of something like showing a list of error descriptions as table header (like Rails apps do).

**Comment by brunow** [comment]
Yes @rpitting that will be the first step. I will do that maybe this week.

**Comment by brunow** [comment]
Basic validation has been added
