### ISSUE TITLE
Is it possible to use without mapping to a custom class?

### ISSUE THREAD

**Issue by testower** [brunow/FormKit.m#33]
Let's say I just want to collect inputs in a dictionary. How would I achieve that?

**Comment by brunow** [comment]
I've not tested, but FormKit use valueForKeyPath to set vars. So it's possible to use it with a dictionary.
You just need to set values to your dict and use it as same as any objects.

```
[FKFormMapping mappingForClass:[NSDictionary class] block:^(FKFormMapping *mapping)
...
[self.formModel loadFieldsWithObject:aDictionary];
```
