### ISSUE TITLE
Keypath save doesn't exist

### ISSUE THREAD

**Issue by jonarrien** [brunow/FormKit.m#34]
I get this error:

> Error FormKitFormMapping keyPath save doesn't exist for object name User . 

This happens when tring to use buttonSave method:

```
[FKFormMapping mappingForClass:[User class] block:^(FKFormMapping *formMapping) {

    // here some fields added without any problem 
    // and this is the line causing the error. 
    [formMapping buttonSave:@"Save" handler:^{
            [self.formModel save];
            [self afterUserSaved];
    }];
}];
[self.formModel loadFieldsWithObject:user];
```

Once the error is printed into the console, FormKit.m doesn't trigger the save event. Any help would be appreciated, thanks.

**Comment by brunow** [comment]
It's only a warning maybe it would be better to completely remove this warning in the future
