### ISSUE TITLE
Keyboard Type

### ISSUE THREAD

**Issue by petermumford** [brunow/FormKit.m#4]
Is there a way of selecting the type of keyboard?

For example I have a FKFormAttributeMappingTypeText and its for the user to enter an email address, I'd like the keyboard type to be UIKeyboardTypeEmailAddress. Or maybe a phone number so I'd like to show UIKeyboardTypeNumberPad.

Please let me know if this is possible, if its not what would be the best approach to accomplish this?

**Comment by brunow** [comment]
I've updated formkit, now you cant do it very simply !

Here's an example:

```
[formMapping mapAttribute:@"numberOfActor" title:@"Number of actor" type:FKFormAttributeMappingTypeInteger   keyboardType:UIKeyboardTypeEmailAddress];
```

**Comment by petermumford** [comment]
Thank you. very simply!
