### ISSUE TITLE
On iOS > 8 row height for invalid rows is wrong.

### ISSUE THREAD

**Issue by ivela-goorkers** [brunow/FormKit.m#41]
In iOS < 8 when a row field is invalid the row height is correctly calculated to display the error message.

But with iOS >= 8 the row height is wrong and the cell doesn't displays well the error message.

I was debugging this and the problem is in this line of FKFormMapper.m:

```
CGFloat rowHeight = attributeMapping.rowHeight > 0 ? attributeMapping.rowHeight : self.tableView.rowHeight;
```

It always returns 0 so then when the cell is updated it height only has the height of the error label (wich is well calculated).

**Comment by brunow** [comment]
I'm sorry but FormKit isn't maintained anymore.
But feel free to fork it for fixing it.
