### ISSUE TITLE
UIPickerView - Crashing

### ISSUE THREAD

**Issue by petermumford** [brunow/FormKit.m#5]
If you don't move the UIPickerView and tap on 'Done' the app will crash every time. If you move the list up and down it will work as normal as it should do.  Please see the error message below:

**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 2147483647 beyond bounds [0 .. 40]'

**Comment by brunow** [comment]
That's because selectedValueIndex is bigger than the array. The picker view doesn't check if array is bigger than selectedValueIndex.
Set the index to 0 at first time and it wont crash.
