### ISSUE TITLE
form mapping to sqlite table?

### ISSUE THREAD

**Issue by gordemota** [brunow/FormKit.m#8]
how to customize it so it form mapping to sqlite table? like given sqlite table name, formkit when save will save it to sqlite table.

**Comment by rpitting** [comment]
Hi Steve,

you should create a custom model class that abstracts your table row (e.g. one row represents one movie). You use this custom class (e.g. Movie.m) as model for your form.

When pressing save, Movie.m has a method that writes it's attributes back to the SQLite database.

**Comment by gordemota** [comment]
thanks
