### ISSUE TITLE
Exception in [FKFormMapper setValue:forAttributeMapping] with CoreData

### ISSUE THREAD

**Issue by msnelling** [brunow/FormKit.m#9]
When I have a CoreData class derived from another I get an exception when updating a field. 

2012-08-19 17:44:49.518 FormKitDemo[1975:c07] **\* WebKit discarded an uncaught exception in the webView:shouldInsertText:replacingDOMRange:givenAction: delegate: <NSInvalidArgumentException> Unacceptable type of value for attribute: property = "numActors"; desired type = NSNumber; given type = __NSCFString; value = 1.

A sample project can be found here https://app.dumptruck.goldenfrog.com/p/I6U688lGVM

**Comment by rpitting** [comment]
FormKit.m does not use UIWebView at all.

Therefore I would say that the error must come from your modifications/code.

**Comment by msnelling** [comment]
I don't use it in my project (or the sample project I provided a link to) either. The sample project above is just a modified version of the FormKitDemo app to use Core Data.

**Comment by msnelling** [comment]
If the link above doesn't work, try this http://dl.dropbox.com/u/3706463/FormKitTest.zip

**Comment by rpitting** [comment]
OK, you are right, the actual issue is:

Invalid values in number fields (e.g. FKFormAttributeMappingTypeInteger) are not safely converted (e.g. when a string is entered).

I will look into the issue.

**Comment by rpitting** [comment]
See commit d961ab50981e64eb817854702d8d4fc8f88a6126 for a fix (pull request already out).

**Comment by msnelling** [comment]
The latest update resolves this issue. Thanks!
